// API: Get Ad
export const GET_AD_SUCCESS = 'GET_AD_SUCCESS';
export const GET_AD_FAILED = 'GET_AD_FAILED';
export const GET_AD_STARTED = 'GET_AD_STARTED';

// API: Get Ad's Friends
export const GET_AD_FRIENDS_SUCCESS = 'GET_AD_FRIENDS_SUCCESS';
export const GET_AD_FRIENDS_FAILED = 'GET_AD_FRIENDS_FAILED';
export const GET_AD_FRIENDS_STARTED = 'GET_AD_FRIENDS_STARTED';

// API: POST Sessions
export const REQUEST_CODE_STARTED = 'REQUEST_CODE_STARTED';
export const REQUEST_CODE_SUCCESS = 'REQUEST_CODE_SUCCESS';
export const REQUEST_CODE_FAILED = 'REQUEST_CODE_FAILED';

// API: Put Sessions
export const SIGN_IN_STARTED = 'SIGN_IN_STARTED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

// API: Delete Sessions
export const SIGN_OUT_STARTED = 'SIGN_OUT_STARTED';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

// API: Put Contacts
export const UPDATE_CONTACTS_STARTED = 'UPDATE_CONTACTS_STARTED';
export const UPDATE_CONTACTS_INITIAL_FINISHED = 'UPDATE_CONTACTS_INITIAL_FINISHED';
export const UPDATE_CONTACTS_FAILED = 'UPDATE_CONTACTS_FAILED';
export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS';
export const UPDATE_CONTACTS_FINISHED = 'UPDATE_CONTACTS_FINISHED';

// API: Get Feed
export const GET_FEED_STARTED = 'GET_FEED_STARTED';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export const GET_FEED_FAILED = 'GET_FEED_FAILED';
export const GET_FEED_NEW_ADS = 'GET_FEED_NEW_ADS';

export const GET_FEED_WITH_OFFSET_STARTED = 'GET_FEED_WITH_OFFSET_STARTED';
export const GET_FEED_WITH_OFFSET_SUCCESS = 'GET_FEED_WITH_OFFSET_SUCCESS';
export const GET_FEED_WITH_OFFSET_FAILED = 'GET_FEED_WITH_OFFSET_FAILED';

// API: Get My Ads
export const GET_MY_ADS_STARTED = 'GET_MY_ADS_STARTED';
export const GET_MY_ADS_SUCCESS = 'GET_MY_ADS_SUCCESS';
export const GET_MY_ADS_FAILED = 'GET_MY_ADS_FAILED';
export const GET_MY_ADS_NEW_ADS = 'GET_MY_ADS_NEW_ADS';

export const GET_MY_ADS_WITH_OFFSET_STARTED = 'GET_MY_ADS_WITH_OFFSET_STARTED';
export const GET_MY_ADS_WITH_OFFSET_SUCCESS = 'GET_MY_ADS_WITH_OFFSET_SUCCESS';
export const GET_MY_ADS_WITH_OFFSET_FAILED = 'GET_MY_ADS_WITH_OFFSET_FAILED';

// API: Get Visited Ads
export const GET_VISITED_ADS_STARTED = 'GET_VISITED_ADS_STARTED';
export const GET_VISITED_ADS_SUCCESS = 'GET_VISITED_ADS_SUCCESS';
export const GET_VISITED_ADS_FAILED = 'GET_VISITED_ADS_FAILED';
export const GET_VISITED_ADS_NEW_ADS = 'GET_VISITED_ADS_NEW_ADS';

export const GET_VISITED_ADS_WITH_OFFSET_STARTED = 'GET_VISITED_ADS_WITH_OFFSET_STARTED';
export const GET_VISITED_ADS_WITH_OFFSET_SUCCESS = 'GET_VISITED_ADS_WITH_OFFSET_SUCCESS';
export const GET_VISITED_ADS_WITH_OFFSET_FAILED = 'GET_VISITED_ADS_WITH_OFFSET_FAILED';

// API: Get Favorite Ads
export const GET_FAVORITE_ADS_STARTED = 'GET_FAVORITE_ADS_STARTED';
export const GET_FAVORITE_ADS_SUCCESS = 'GET_FAVORITE_ADS_SUCCESS';
export const GET_FAVORITE_ADS_FAILED = 'GET_FAVORITE_ADS_FAILED';
export const GET_FAVORITE_ADS_NEW_ADS = 'GET_FAVORITE_ADS_NEW_ADS';

export const GET_FAVORITE_ADS_WITH_OFFSET_STARTED = 'GET_FAVORITE_ADS_WITH_OFFSET_STARTED';
export const GET_FAVORITE_ADS_WITH_OFFSET_SUCCESS = 'GET_FAVORITE_ADS_WITH_OFFSET_SUCCESS';
export const GET_FAVORITE_ADS_WITH_OFFSET_FAILED = 'GET_FAVORITE_ADS_WITH_OFFSET_FAILED';

// API: Create Favorite Ad
export const LIKE_AD = 'LIKE_AD';

// API: Destroy Favorite Ad
export const UNLIKE_AD = 'UNLIKE_AD';

// API: Delete Contacts
export const DELETE_CONTACTS = 'DELETE_CONTACTS';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_FAILED = 'DELETE_CONTACTS_FAILED';

// API Get UserContacts
export const GET_USER_CONTACTS_STARTED = 'GET_USER_CONTACTS_STARTED';
export const GET_USER_CONTACTS_SUCCESS = 'GET_USER_CONTACTS_SUCCESS';
export const GET_USER_CONTACTS_NEW_CONTACT = 'GET_USER_CONTACTS_NEW_CONTACT';
export const GET_USER_CONTACTS_FAILED = 'GET_USER_CONTACTS_FAILED';
export const GET_USER_CONTACTS_NEW_CONTACTS = 'GET_USER_CONTACTS_NEW_CONTACTS';

export const GET_USER_CONTACTS_WITH_OFFSET_STARTED = 'GET_USER_CONTACTS_WITH_OFFSET_STARTED';
export const GET_USER_CONTACTS_WITH_OFFSET_SUCCESS = 'GET_USER_CONTACTS_WITH_OFFSET_SUCCESS';
export const GET_USER_CONTACTS_WITH_OFFSET_FAILED = 'GET_USER_CONTACTS_WITH_OFFSET_FAILED';

export const USER_CONTACTS_UPDATE_QUERY = 'USER_CONTACTS_UPDATE_QUERY';

// API Get Profile
export const GET_PROFILE_STARTED = 'GET_PROFILE_STARTED';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

// API Put Profile
export const UPDATE_PROFILE_STARTED = 'UPDATE_PROFILE_STARTED';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

// MISC
export const SET_ERROR = 'SET_ERROR';
export const SET_WIZARD_DONE = 'SET_WIZARD_DONE';
export const FILTER_CHANGED = 'FILTER_CHANGED';
export const FILTER_RESET = 'FILTER_RESET';
export const FILTER_CHANGED_ARRAY = 'FILTER_CHANGED_ARRAY';
export const FILTER_VALUES_UPDATE = 'FILTER_VALUES_UPDATE';
export const FILTER_MODAL_SWITCH_VISIBILITY = 'FILTER_MODAL_SWITCH_VISIBILITY';

// AUTH
export const AUTH_PHONE_CHANGED = 'AUTH_PHONE_CHANGED';
export const AUTH_CODE_CHANGED = 'AUTH_CODE_CHANGED';
export const AUTH_CODE_IS_INVALID_FORMAT = 'AUTH_CODE_IS_INVALID_FORMAT';
export const AUTH_PHONE_IS_INVALID_FORMAT = 'AUTH_PHONE_IS_INVALID_FORMAT';
export const AUTH_RESET = 'AUTH_RESET';
export const PHONE_FROM_CACHE = 'PHONE_FROM_CACHE';

// PERMISSIONS
export const CONTACTS_PERMISSIONS_DENIED = 'CONTACTS_PERMISSIONS_DENIED';
export const CONTACTS_PERMISSIONS_GIVEN = 'CONTACTS_PERMISSIONS_GIVEN';
export const CONTACTS_PERMISSIONS_MAY_BE_REQUESTED = 'CONTACTS_PERMISSIONS_MAY_BE_REQUESTED';
export const CONTACTS_PERMISSIONS_WERE_REQUESTED = 'CONTACTS_PERMISSIONS_WERE_REQUESTED';

export const NOTIFICATIONS_PERMISSIONS_DENIED = 'NOTIFICATIONS_PERMISSIONS_DENIED';
export const NOTIFICATIONS_PERMISSIONS_GIVEN = 'NOTIFICATIONS_PERMISSIONS_GIVEN';
export const NOTIFICATIONS_PERMISSIONS_STARTED = 'NOTIFICATIONS_PERMISSIONS_STARTED';


// Starred Ad Tab
export const GET_STARRED_AD_SUCCESS = 'GET_STARRED_AD_SUCCESS';
export const GET_STARRED_AD_STARTED = 'GET_STARRED_AD_STARTED';
export const GET_STARRED_AD_FAILED = 'GET_STARRED_AD_FAILED';
export const GET_STARRED_AD_FRIENDS_STARTED = 'GET_STARRED_AD_FRIENDS_STARTED';
export const GET_STARRED_AD_FRIENDS_FAILED = 'GET_STARRED_AD_FRIENDS_FAILED';
export const GET_STARRED_AD_FRIENDS_SUCCESS = 'GET_STARRED_AD_FRIENDS_SUCCESS';
