// API: Get ChatRooms
export const GET_CHAT_ROOMS_STARTED = 'GET_CHAT_ROOMS_STARTED';
export const GET_CHAT_ROOMS_SUCCESS = 'GET_CHAT_ROOMS_SUCCESS';
export const GET_CHAT_ROOMS_FAILED = 'GET_CHAT_ROOMS_FAILED';

// API: Get Admin ChatRooms
export const GET_ADMIN_CHAT_ROOMS_STARTED = 'GET_ADMIN_CHAT_ROOMS_STARTED';
export const GET_ADMIN_CHAT_ROOMS_SUCCESS = 'GET_ADMIN_CHAT_ROOMS_SUCCESS';
export const GET_ADMIN_CHAT_ROOMS_FAILED = 'GET_ADMIN_CHAT_ROOMS_FAILED';

// export const GET_CHAT_ROOMS_WITH_OFFSET_STARTED = 'GET_CHAT_ROOMS_WITH_OFFSET_STARTED';
// export const GET_CHAT_ROOMS_WITH_OFFSET_SUCCESS = 'GET_CHAT_ROOMS_WITH_OFFSET_SUCCESS';
// export const GET_CHAT_ROOMS_WITH_OFFSET_FAILED = 'GET_CHAT_ROOMS_WITH_OFFSET_FAILED';

// API: Get Ad
export const GET_AD_SUCCESS = 'GET_AD_SUCCESS';
export const GET_AD_FAILED = 'GET_AD_FAILED';
export const GET_AD_STARTED = 'GET_AD_STARTED';

// API: Create Ad
export const CREATE_AD_STARTED = 'CREATE_AD_STARTED';
export const CREATE_AD_SUCCESS = 'CREATE_AD_SUCCESS';
export const CREATE_AD_FAILED = 'CREATE_AD_FAILED';

// API: Update Ad
export const UPDATE_AD_STARTED = 'UPDATE_AD_STARTED';
export const UPDATE_AD_SUCCESS = 'UPDATE_AD_SUCCESS';
export const UPDATE_AD_FAILED = 'UPDATE_AD_FAILED';

// API: Delete Ad
export const DELETE_AD_STARTED = 'DELETE_AD_STARTED';
export const DELETE_AD_SUCCESS = 'DELETE_AD_SUCCESS';
export const DELETE_AD_FAILED = 'DELETE_AD_FAILED';

// API: Archive Ad
export const ARCHIVE_AD_STARTED = 'ARCHIVE_AD_STARTED';
export const ARCHIVE_AD_SUCCESS = 'ARCHIVE_AD_SUCCESS';
export const ARCHIVE_AD_FAILED = 'ARCHIVE_AD_FAILED';

// API: Unarchive Ad
export const UNARCHIVE_AD_STARTED = 'UNARCHIVE_AD_STARTED';
export const UNARCHIVE_AD_SUCCESS = 'UNARCHIVE_AD_SUCCESS';
export const UNARCHIVE_AD_FAILED = 'UNARCHIVE_AD_FAILED';

// API: Get Ad's Friends
export const GET_AD_FRIENDS_SUCCESS = 'GET_AD_FRIENDS_SUCCESS';
export const GET_AD_FRIENDS_FAILED = 'GET_AD_FRIENDS_FAILED';
export const GET_AD_FRIENDS_STARTED = 'GET_AD_FRIENDS_STARTED';

// API: POST Sessions
export const REQUEST_CODE_STARTED = 'REQUEST_CODE_STARTED';
export const REQUEST_CODE_SUCCESS = 'REQUEST_CODE_SUCCESS';
export const REQUEST_CODE_FAILED = 'REQUEST_CODE_FAILED';

// API: Put Sessions
export const SIGN_IN_STARTED = 'SIGN_IN_STARTED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

// API: Delete Sessions
export const SIGN_OUT_STARTED = 'SIGN_OUT_STARTED';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

// API: Put Contacts
export const UPDATE_CONTACTS_STARTED = 'UPDATE_CONTACTS_STARTED';
export const UPDATE_CONTACTS_INITIAL_FINISHED = 'UPDATE_CONTACTS_INITIAL_FINISHED';
export const UPDATE_CONTACTS_FAILED = 'UPDATE_CONTACTS_FAILED';
export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS';
export const UPDATE_CONTACTS_FINISHED = 'UPDATE_CONTACTS_FINISHED';

// API: Get Feed
export const GET_FEED_STARTED = 'GET_FEED_STARTED';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export const GET_FEED_FAILED = 'GET_FEED_FAILED';
export const GET_FEED_NEW_ADS = 'GET_FEED_NEW_ADS';

export const GET_FEED_WITH_OFFSET_STARTED = 'GET_FEED_WITH_OFFSET_STARTED';
export const GET_FEED_WITH_OFFSET_SUCCESS = 'GET_FEED_WITH_OFFSET_SUCCESS';
export const GET_FEED_WITH_OFFSET_FAILED = 'GET_FEED_WITH_OFFSET_FAILED';

// API: Get My Ads
export const GET_MY_ADS_STARTED = 'GET_MY_ADS_STARTED';
export const GET_MY_ADS_SUCCESS = 'GET_MY_ADS_SUCCESS';
export const GET_MY_ADS_FAILED = 'GET_MY_ADS_FAILED';
export const GET_MY_ADS_NEW_ADS = 'GET_MY_ADS_NEW_ADS';

export const GET_MY_ADS_WITH_OFFSET_STARTED = 'GET_MY_ADS_WITH_OFFSET_STARTED';
export const GET_MY_ADS_WITH_OFFSET_SUCCESS = 'GET_MY_ADS_WITH_OFFSET_SUCCESS';
export const GET_MY_ADS_WITH_OFFSET_FAILED = 'GET_MY_ADS_WITH_OFFSET_FAILED';

// API: Get Visited Ads
export const GET_VISITED_ADS_STARTED = 'GET_VISITED_ADS_STARTED';
export const GET_VISITED_ADS_SUCCESS = 'GET_VISITED_ADS_SUCCESS';
export const GET_VISITED_ADS_FAILED = 'GET_VISITED_ADS_FAILED';
export const GET_VISITED_ADS_NEW_ADS = 'GET_VISITED_ADS_NEW_ADS';

export const GET_VISITED_ADS_WITH_OFFSET_STARTED = 'GET_VISITED_ADS_WITH_OFFSET_STARTED';
export const GET_VISITED_ADS_WITH_OFFSET_SUCCESS = 'GET_VISITED_ADS_WITH_OFFSET_SUCCESS';
export const GET_VISITED_ADS_WITH_OFFSET_FAILED = 'GET_VISITED_ADS_WITH_OFFSET_FAILED';

// API: Get Favorite Ads
export const GET_FAVORITE_ADS_STARTED = 'GET_FAVORITE_ADS_STARTED';
export const GET_FAVORITE_ADS_SUCCESS = 'GET_FAVORITE_ADS_SUCCESS';
export const GET_FAVORITE_ADS_FAILED = 'GET_FAVORITE_ADS_FAILED';
export const GET_FAVORITE_ADS_NEW_ADS = 'GET_FAVORITE_ADS_NEW_ADS';

export const GET_FAVORITE_ADS_WITH_OFFSET_STARTED = 'GET_FAVORITE_ADS_WITH_OFFSET_STARTED';
export const GET_FAVORITE_ADS_WITH_OFFSET_SUCCESS = 'GET_FAVORITE_ADS_WITH_OFFSET_SUCCESS';
export const GET_FAVORITE_ADS_WITH_OFFSET_FAILED = 'GET_FAVORITE_ADS_WITH_OFFSET_FAILED';

// API: Create Favorite Ad
export const LIKE_AD = 'LIKE_AD';

// API: Destroy Favorite Ad
export const UNLIKE_AD = 'UNLIKE_AD';

// API: Delete Contacts
export const DELETE_CONTACTS = 'DELETE_CONTACTS';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_FAILED = 'DELETE_CONTACTS_FAILED';

// API: Get Messages
export const SYNC_MESSAGES_STARTED = 'SYNC_MESSAGES_STARTED';
export const SYNC_MESSAGES_SUCCESS = 'SYNC_MESSAGES_SUCCESS';
export const GET_MESSAGES_WITH_OFFSET_STARTED = 'GET_MESSAGES_WITH_OFFSET_STARTED';
export const GET_MESSAGES_WITH_OFFSET_SUCCESS = 'GET_MESSAGES_WITH_OFFSET_SUCCESS';
export const GET_MESSAGES_WITH_OFFSET_FAILED = 'GET_MESSAGES_WITH_OFFSET_FAILED';

// API Get UserContacts
export const GET_USER_CONTACTS_STARTED = 'GET_USER_CONTACTS_STARTED';
export const GET_USER_CONTACTS_SUCCESS = 'GET_USER_CONTACTS_SUCCESS';
export const GET_USER_CONTACTS_NEW_CONTACT = 'GET_USER_CONTACTS_NEW_CONTACT';
export const GET_USER_CONTACTS_FAILED = 'GET_USER_CONTACTS_FAILED';
export const GET_USER_CONTACTS_NEW_CONTACTS = 'GET_USER_CONTACTS_NEW_CONTACTS';

export const GET_USER_CONTACTS_WITH_OFFSET_STARTED = 'GET_USER_CONTACTS_WITH_OFFSET_STARTED';
export const GET_USER_CONTACTS_WITH_OFFSET_SUCCESS = 'GET_USER_CONTACTS_WITH_OFFSET_SUCCESS';
export const GET_USER_CONTACTS_WITH_OFFSET_FAILED = 'GET_USER_CONTACTS_WITH_OFFSET_FAILED';

export const USER_CONTACTS_UPDATE_QUERY = 'USER_CONTACTS_UPDATE_QUERY';

// API Get Profile
export const GET_PROFILE_STARTED = 'GET_PROFILE_STARTED';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

// API Put Profile
export const UPDATE_PROFILE_STARTED = 'UPDATE_PROFILE_STARTED';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

// MISC
export const SET_ERROR = 'SET_ERROR';
export const SET_WIZARD_DONE = 'SET_WIZARD_DONE';
export const FILTER_CHANGED = 'FILTER_CHANGED';
export const FILTER_RESET = 'FILTER_RESET';
export const FILTER_CHANGED_ARRAY = 'FILTER_CHANGED_ARRAY';
export const FILTER_MODAL_SWITCH_VISIBILITY = 'FILTER_MODAL_SWITCH_VISIBILITY';
export const POST_MESSAGE = 'POST_MESSAGE';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const SET_CURRENT_ADMIN_CHAT = 'SET_CURRENT_ADMIN_CHAT';
export const INITIATE_SYSTEM_CHAT = 'INITIATE_SYSTEM_CHAT';
export const RESET_ADS_LISTS_AD = 'RESET_ADS_LISTS_AD';
export const REMOVE_RESET_ADS_LISTS_AD = 'REMOVE_RESET_ADS_LISTS_AD';
export const RESET_FEED_AD = 'RESET_FEED_AD';
export const REMOVE_RESET_FEED_AD = 'REMOVE_RESET_FEED_AD';
export const SET_CURRENT_TAB_ADS_LISTS = 'SET_CURRENT_TAB_ADS_LISTS';

// API Get Settings
export const GET_SETTINGS_STARTED = 'GET_SETTINGS_STARTED';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAILED = 'GET_SETTINGS_FAILED';

// AUTH
export const AUTH_PHONE_CHANGED = 'AUTH_PHONE_CHANGED';
export const AUTH_CODE_CHANGED = 'AUTH_CODE_CHANGED';
export const AUTH_RESET = 'AUTH_RESET';
export const PHONE_FROM_CACHE = 'PHONE_FROM_CACHE';

// PERMISSIONS
export const CONTACTS_PERMISSIONS_DENIED = 'CONTACTS_PERMISSIONS_DENIED';
export const CONTACTS_PERMISSIONS_GIVEN = 'CONTACTS_PERMISSIONS_GIVEN';
export const CONTACTS_PERMISSIONS_MAY_BE_REQUESTED = 'CONTACTS_PERMISSIONS_MAY_BE_REQUESTED';
export const CONTACTS_PERMISSIONS_WERE_REQUESTED = 'CONTACTS_PERMISSIONS_WERE_REQUESTED';

export const NOTIFICATIONS_PERMISSIONS_DENIED = 'NOTIFICATIONS_PERMISSIONS_DENIED';
export const NOTIFICATIONS_PERMISSIONS_GIVEN = 'NOTIFICATIONS_PERMISSIONS_GIVEN';
export const NOTIFICATIONS_PERMISSIONS_STARTED = 'NOTIFICATIONS_PERMISSIONS_STARTED';

// AdsLists Ad Tab
export const GET_ADS_LISTS_AD_SUCCESS = 'GET_ADS_LISTS_AD_SUCCESS';
export const GET_ADS_LISTS_AD_STARTED = 'GET_ADS_LISTS_AD_STARTED';
export const GET_ADS_LISTS_AD_FAILED = 'GET_ADS_LISTS_AD_FAILED';
export const GET_ADS_LISTS_AD_FRIENDS_STARTED = 'GET_ADS_LISTS_AD_FRIENDS_STARTED';
export const GET_ADS_LISTS_AD_FRIENDS_FAILED = 'GET_ADS_LISTS_AD_FRIENDS_FAILED';
export const GET_ADS_LISTS_AD_FRIENDS_SUCCESS = 'GET_ADS_LISTS_AD_FRIENDS_SUCCESS';

// Chat Ad Friends
export const GET_CHAT_AD_FRIENDS_STARTED = 'GET_CHAT_AD_FRIENDS_STARTED';
export const GET_CHAT_AD_FRIENDS_FAILED = 'GET_CHAT_AD_FRIENDS_FAILED';
export const GET_CHAT_AD_FRIENDS_SUCCESS = 'GET_CHAT_AD_FRIENDS_SUCCESS';

export const LEAVE_CHAT_SUCCESS = 'LEAVE_CHAT_SUCCESS';
export const MESSAGE_WAS_READ = 'MESSAGE_WAS_READ';
export const UPDATE_UNREAD_MESSAGES_COUNT = 'UPDATE_UNREAD_MESSAGES_COUNT';
export const MESSAGE_WAS_DELETED = 'MESSAGE_WAS_DELETED';
export const MESSAGE_IS_DELETING = 'MESSAGE_IS_DELETING';
export const RESET_CURRENT_CHAT = 'RESET_CURRENT_CHAT';
export const RESET_CURRENT_ADMIN_CHAT = 'RESET_CURRENT_ADMIN_CHAT';

// Toggle Block
export const USER_CONTACTS_TOGGLE_BLOCK_SUCCESS = 'USER_CONTACTS_TOGGLE_BLOCK_SUCCESS';
export const USER_CONTACTS_TOGGLE_BLOCK_FAILED = 'USER_CONTACTS_TOGGLE_BLOCK_FAILED';
